server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health, info, git, loggers, beans

logging:
  level.root: debug
  # level.org.hibernate.SQL: DEBUG
  # level.liquibase: INFO
  level.io.fdlessard.codebites.batch: DEBUG

spring:
  application:
    name: batch-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  batch:
    job:
      enabled: false
    initialize-schema: always


#  datasource:
#    username: ${POSTGRES_USER:postgres}
#    password: ${POSTGRES_PASSWORD:secret}
#    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:postgres}
#    initialization-mode: always
#    separator: ";;"
#    schema: classpath:/db/scripts/create-postgres-schema.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          create_namespaces: true
          auto: update
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#    hibernate:
#      ddl-auto: create
#      use-new-id-generator-mappings: false
#      jdbc:
#        time_zone: UTC
#    show-sql: true
#  liquibase:
#    enabled: on
#    drop-first: on
#    default-schema: public
#    change-log: classpath:/db/changelog/db.changelog-master.yaml

cust1:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}

cust2:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}

batch:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}



inputFile: classpath:/customer.csv




