server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health, info, git, loggers, beans

logging:
  level.root: debug
  # level.org.hibernate.SQL: DEBUG
  # level.liquibase: INFO
  level.io.fdlessard.codebites.batch: DEBUG

spring:
  application:
    name: batch-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  h2:
    console:
      enabled: false
  batch:
    job:
      enabled: false
    initialize-schema: always

batch:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

cust1:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret

cust2:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret





inputFile: classpath:/customer.csv




